Change methods to inline so as to avoid naming clashes
KhronosGroup/SyclParallelSTL pull request #62
Opened 2018-02-02 13:44 UTC by domantasjurkus

2018-02-26 13:49 UTC, cjdb commented on include/sycl/algorithm/buffer_algorithms.hpp
> +inline size_t up_rounded_division(size_t x, size_t y){
Let's make this one `constexpr` instead of `inline`.

2018-02-26 13:51 UTC, cjdb commented
Looks good, I'll merge after `up_rounded_division` is specified as `constexpr`.

2018-03-15 15:50 UTC, keryell requested changes
Yes, please use `constexpr`.
Note that this implies under the hood `inline` that you do not need to repeat.

2018-03-15 15:51 UTC, keryell commented
It would be also nice to have a unit test case showing the issue and to check the problem is solved.
Thanks.

2018-06-13 16:38 UTC, keryell commented
What is the current mood about this?

2019-12-02 15:08 UTC, keryell commented
Any feedback?

2024-01-26 10:54 UTC, closed without merging